### ISSUE TITLE
On-chain group admin problems and feature suggestions

### ISSUE THREAD

**Issue by Insun35** [interep-project/contracts#10]
1. Admin transfer 
    For now, It seems admin cannot be transferred to another address when the admin address has a problem

2. All gas fees for group join/leave are borne by the admin. 
    Are there any solutions? (.e.g admin only makes the signature for just approving join/leave)

**Comment by cedoor** [comment]
Hi @Insun35 ,

1. You're right, contracts are currently very basic. Some controls are also missing, I'll work on updating them right away.
2. This could be a good solution. I'll add it to the tasks for later discussion.
